@startuml schema-diagram

frame BaseObject {
	' FirebaseBaseObject
	object FirebaseBase {
		createdAt: Firebase.timestamp
		updatedAt: Firebase.timestamp
		createdUser: Users.id
		updatedUser: Users.id
	}
	object ClientBase {
		id: Firebase.Doc.id
	}
}

package Domain {
	frame User {
		object Users {
			uid: FirebaseAuth.uid
			username: string;
		}
	}

	frame Group {
		object Groups {
			owner: Users.id
			name: string
			description: string
			members: Users.id[]
		}
	}

	frame Project { 
		object Projects {
			group: Groups.id
			name: string
			description: string
		}

		object ProjectMembers {
			project: Projects.id
			user: Users.id
			auth: ?
		}
	}

	frame Skill { 
		object SkillCategories {
			project: Projects.id
			name: string
			description: string
		}

		object SkillLevels {
			project: Projects.id
			order: number
			icon: string
			name: string
			description: string
		}

		object Skills {
			project: Projects.id
			category: SkillCategories.id
			name: string
		}

		object SkillDiscriptions {
			project: Projects.id
			lebel: SkillLevels.id
			skill: Skills.id
			description: string
		}

		object UsersSkills {
			project: Projects.id
			user: Users.id
			skill: Skill.id
			grows: string
			description: string
		}
	}
}

package ReduxStore {
	frame userFeature {
		object user {
			id: string
			uid: string
			username: string
		}
	}

	frame groupFeature {
		object ownerGroup {
			id: string
			groupMembers: Users[]
		}
		object belongedToGroup {
		}
	}

	frame projectFeature {
		object project {
		}
	}
}

@enduml